a = input('Digite algo: ')
print('O tipo primitivo é: ', type(a))
print('Só tem espaço?', a.isspace())
print('É um número? ', a.isnumeric())
print('É alfabetico?', a.isalpha())
print('É alfanumerico?', a.isalnum())
print('Está em maiusula?', a.isupper())
print('Está em minuscula?', a.islower())
print('Está capitalizada', a.istitle())
